### PR TITLE
Added SOTA feature extractor methods (EigenPlaces, CosPlace)

### PR DESCRIPTION
**Pull request by gmberton**
Hi @stschubert @Tobias-Fischer,
following [this issue](https://github.com/stschubert/VPR_Tutorial/issues/6) I've added two recent global features extraction methods, namely CosPlace (CVPR 2022) and EigenPlaces (ICCV 2023).
I ran the `demo.py` with both methods and it works fine.
I hope it fits properly with the rest of the repo.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Looks good to me, thank you @gmberton!

Happy for you to merge @stschubert.

At some point we should look into avoiding unnecessary code duplication for the transforms etc., but we can do that independently of this PR.

**Comment by gmberton** [comment]
Thank you @Tobias-Fischer!
I totally agree that it would be better to avoid code duplication for the data part, if you would like me to contribute I'm happy to help :-)

**Comment by stschubert** [comment]
Hi @gmberton,
Sorry, I've been a bit busy the last few days (had my PhD defense). Thank you very much for your contribution. I've tested your code. Works fine, great job!

**Comment by gmberton** [comment]
Great, I'm happy to contribute! And @stschubert congrats on your PhD defense!

**Pull request merged**
